create table if not exists public.site_settings (
  id bigint primary key,
  hero_name_top text,
  hero_name_bottom text,
  bg_color text,
  font_family text,
  profile_image_url text
);

alter table public.site_settings enable row level security;

drop policy if exists "public read settings" on public.site_settings;
create policy "public read settings" on public.site_settings
for select to anon using (true);

drop policy if exists "anon upsert settings" on public.site_settings;
create policy "anon upsert settings" on public.site_settings
for all to anon using (true) with check (true);



-- Run this in Supabase SQL Editor

alter table public.site_settings
  add column if not exists cv_file_url text,
  add column if not exists cv_file_name text,
  add column if not exists favicon_url text,
  add column if not exists about_title text,
  add column if not exists about_text1 text,
  add column if not exists about_text2 text,
  add column if not exists seo_site_title text,
  add column if not exists seo_site_description text,
  add column if not exists seo_site_keywords text,
  add column if not exists seo_og_image_url text,
  add column if not exists seo_twitter_title text,
  add column if not exists seo_twitter_description text,
  add column if not exists seo_twitter_image_url text,
  add column if not exists seo_indexing_enabled boolean default true,
  add column if not exists seo_canonical_base_url text;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  event_date date,
  location text,
  excerpt text,
  content_html text,
  cover_image_url text not null,
  gallery_image_1 text,
  gallery_image_2 text,
  gallery_image_3 text,
  gallery_image_4 text,
  sort_order integer default 0,
  featured boolean default true,
  enabled boolean default true,
  seo_title text,
  seo_description text,
  seo_keywords text,
  og_image_url text,
  canonical_url text,
  created_at timestamptz default now()
);

create table if not exists public.cv_downloads (
  id bigint generated by default as identity primary key,
  visitor_token text,
  page_key text,
  user_agent text,
  referrer text,
  created_at timestamptz default now()
);

alter table public.events enable row level security;
alter table public.cv_downloads enable row level security;

drop policy if exists "public read events" on public.events;
create policy "public read events" on public.events
for select to anon using (true);

drop policy if exists "anon manage events" on public.events;
create policy "anon manage events" on public.events
for all to anon using (true) with check (true);

drop policy if exists "anon insert cv downloads" on public.cv_downloads;
create policy "anon insert cv downloads" on public.cv_downloads
for insert to anon with check (true);

drop policy if exists "anon read cv downloads" on public.cv_downloads;
create policy "anon read cv downloads" on public.cv_downloads
for select to anon using (true);

insert into storage.buckets (id, name, public)
values ('documents', 'documents', true)
on conflict (id) do nothing;
